myapp/urls.py
from django.urls import path, include
from .views import *

app_name = 'myapp'
urlpatterns = [
    path('',      top,         name='view_top'),
    path('add/',  add_person,  name='view_add_person'),
]

mysite/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

myapp/models.py
from django.db import models

class Person(models.Model):
    name     = models.CharField(verbose_name='氏名', max_length=50, default='')
    age      = models.IntegerField(verbose_name='年齢', default=0)
    objects  = models.Manager()
    def __str__(self):
        return "%s(%d)" % (self.name, age)

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *

@login_required
def top(request):
    user = request.user.username
    people = Person.objects.using(user).all()
    return render(request, 'top.html', {'user':user,'people':people})

@login_required
def add_person(request):
    if request.method == 'GET':
        return render(request, 'add.html')
    else:
        user = request.user.username
        name  = request.POST.get('name')
        age   = request.POST.get('age')
        person = Person(name=name, age=age)
        person.save(using=user)
        return redirect('myapp:view_top')

myapp/templates/add.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add|MultiUserDB</title>
  </head>
  <body>
		<form id="add_person" action="{% url 'myapp:view_add_person' %}" method="post">
			{% csrf_token %}
			name<br>
			<input type="text" name="name" value=""><br>
			age<br>
			<input type="text" name="age" value=""><br>
			<input type="submit" value="save" />
		</form>
</body>
</html>

myapp/templates/top.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MultiUserDB</title>
  </head>
  <body>
    Hello {{user}}!<br>
    <table>
  		<tr><th>Name</th><th>Age</th></tr>
  	  {% for person in people %}
  	  	<tr><td>{{ person.name }}</td><td>{{ person.age }}</td></tr>
  	  {% endfor %}
  	</table>
    <a href="{% url 'myapp:view_add_person' %}">Add Person</a><br>
    <a href="{% url 'login' %}">Logout</a>
  </body>
</html>